[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "https://eth-sepolia.g.alchemy.com/v2/a0YdfR1LJHHBqMHPHXKolJjfUxkSRutL", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/a0YdfR1LJHHBqMHPHXKolJjfUxkSRutL" }
remapping = [
    '@chainlink=lib/chainlink/contracts/src/v0.8',
    '@openzeppelin=lib/openzeppelin-contracts/contracts',
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
